puts "Seeding users..."
u1 = User.create(name: 'James', profile_img: 'https://i.ibb.co/d4yRDDp/james.png', password: 'password', password_confirmation: 'password')
u2 = User.create(name: 'William', profile_img: 'https://i.ibb.co/gvDjkNj/william.png', password: 'password', password_confirmation: 'password')
u3 = User.create(name: 'Tashi', profile_img: 'https://i.ibb.co/C15mvV5/tashi.png', password: 'password', password_confirmation: 'password')
u4 = User.create(name: 'Corey', profile_img: 'https://i.ibb.co/Wy8Q5qd/corey.png', password: 'password', password_confirmation: 'password')
u5 = User.create(name: 'Sinclair', profile_img: 'https://i.ibb.co/dJ13ftd/sinclair.png', password: 'password', password_confirmation: 'password')
u5 = User.create(name: 'Micaela', profile_img: 'https://i.ibb.co/SKgqB9P/micaela.png', password: 'password', password_confirmation: 'password')
u6 = User.create(name: 'Akilah', profile_img: 'https://i.ibb.co/GVSMZ6v/akilah.png', password: 'password', password_confirmation: 'password')
u7 = User.create(name: 'Osvaldo', profile_img: 'https://i.ibb.co/1mGxsmt/osvaldo.png', password: 'password', password_confirmation: 'password')
u8 = User.create(name: 'Norah', profile_img: 'https://i.ibb.co/gWPfbRg/norah.png', password: 'password', password_confirmation: 'password')
u9 = User.create(name: 'Peachy', profile_img: 'https://i.ibb.co/MkmfYtm/peachy.png', password: 'password', password_confirmation: 'password')
u10 = User.create(name: 'Robert', profile_img: 'https://i.ibb.co/ZmC5rkL/robert.png', password: 'password', password_confirmation: 'password')
u11 = User.create(name: 'Ludwig', profile_img: 'https://i.ibb.co/72j091r/ludwig.png', password: 'password', password_confirmation: 'password')
u12 = User.create(name: 'Mark', profile_img: 'https://i.ibb.co/VjcK3sk/mark.png', password: 'password', password_confirmation: 'password')
u13 = User.create(name: 'Yax', profile_img: 'https://i.ibb.co/pvprrCS/yax.png', password: 'password', password_confirmation: 'password')
u14 = User.create(name: 'Yeming', profile_img: 'https://i.ibb.co/8PK4SLK/yeming.png', password: 'password', password_confirmation: 'password')
u15 = User.create(name: 'Yixin', profile_img: 'https://i.ibb.co/nMg3c35/yixin.png', password: 'password', password_confirmation: 'password')
u16 = User.create(name: 'Em', profile_img: 'https://i.ibb.co/4F4zRWk/em.png', password: 'password', password_confirmation: 'password')
u17 = User.create(name: 'Jonathan', profile_img: 'https://i.ibb.co/vmqGfN4/jonathan.png', password: 'password', password_confirmation: 'password')
u18 = User.create(name: 'Kenneth', profile_img: 'https://i.ibb.co/pxTYqWQ/kenneth.png', password: 'password', password_confirmation: 'password')
u19 = User.create(name: 'Leigh', profile_img: 'https://i.ibb.co/XVmYhJy/leigh.png', password: 'password', password_confirmation: 'password')
u20 = User.create(name: 'Omar', profile_img: 'https://i.ibb.co/bQ7Lrqv/link2.png', password: 'password', password_confirmation: 'password')
u21 = User.create(name: 'Nyi', profile_img: 'https://i.ibb.co/PGDKPjt/nyi.png', password: 'password', password_confirmation: 'password')


puts "Seeding items..."
i1 = Item.create(name: "Sword", img_url: "https://freesvg.org/img/Anonymous-katana.png", description:"the sword of King James")
i2 = Item.create(name: "Cap", img_url: "http://cdn.shopify.com/s/files/1/0354/5271/5148/products/20957832_03_1200x630.jpg?v=1643649658", description:"Mark's cap")
i3 = Item.create(name: "Shield", img_url: "https://freesvg.org/img/Chrisdesign_weapon_shield.png", description:"Shield of nonsense")
i4 = Item.create(name: "Laptop", img_url: "https://freesvg.org/img/laptop-personification-work-ready-body-builder.png", description:"Mohammed's laptop, full of code")
i5 = Item.create(name: "Hand Sanitizer", img_url: "https://upload.wikimedia.org/wikipedia/commons/7/71/Purell_Hand_Sanitizer_%2816066200780%29.jpg", description:"Purell")



puts "Seeding powers..."
Power.create(name: "Poke", str: 1, hp: 2, description: "poking motions", user_id: u1.id, item_id: i4.id)
Power.create(name: "Headbutt", str: 2, hp: 1, description: "head to butt motions", user_id: u2.id, item_id: i1.id)
Power.create(name: "Push", str: 1, hp: 1, description: "Hard shove without you seeing it coming", user_id: u3.id, item_id: i2.id)
Power.create(name: "Slap", str: 1, hp: 1, description: "What did the five fingers say to the face?", user_id: u4.id, item_id: i4.id)
Power.create(name: "Sanitize", str: 1, hp: 1, description: "99.98% effective", user_id: u5.id, item_id: i1.id)
Power.create(name: "Fart", str: 1, hp: 1, description: "Putrid gas attack", user_id: u6.id, item_id: i2.id)
Power.create(name: "Poke", str: 1, hp: 2, description: "poking motions", user_id: u7.id, item_id: i4.id)
Power.create(name: "Headbutt", str: 2, hp: 1, description: "head to butt motions", user_id: u8.id, item_id: i1.id)
Power.create(name: "Push", str: 1, hp: 1, description: "Hard shove without you seeing it coming", user_id: u9.id, item_id: i3.id)
Power.create(name: "Slap", str: 1, hp: 1, description: "What did the five fingers say to the face?", user_id: u10.id, item_id: i4.id)
Power.create(name: "Sanitize", str: 1, hp: 1, description: "99.98% effective", user_id: u11.id, item_id: i1.id)
Power.create(name: "Fart", str: 1, hp: 1, description: "Putrid gas attack", user_id: u12.id, item_id: i2.id)
Power.create(name: "Poke", str: 1, hp: 2, description: "poking motions", user_id: u13.id, item_id: i4.id)
Power.create(name: "Headbutt", str: 2, hp: 1, description: "head to butt motions", user_id: u14.id, item_id: i1.id)
Power.create(name: "Push", str: 1, hp: 1, description: "Hard shove without you seeing it coming", user_id: u15.id, item_id: i3.id)
Power.create(name: "Slap", str: 1, hp: 1, description: "What did the five fingers say to the face?", user_id: u16.id, item_id: i4.id)
Power.create(name: "Sanitize", str: 1, hp: 1, description: "99.98% effective", user_id: u17.id, item_id: i1.id)
Power.create(name: "Fart", str: 1, hp: 1, description: "Putrid gas attack", user_id: u18.id, item_id: i5.id)
Power.create(name: "Poke", str: 1, hp: 2, description: "poking motions", user_id: u19.id, item_id: i5.id)
Power.create(name: "Headbutt", str: 2, hp: 1, description: "head to butt motions", user_id: u20.id, item_id: i1.id)
Power.create(name: "Push", str: 1, hp: 1, description: "Hard shove without you seeing it coming", user_id: u21.id, item_id: i2.id)
Power.create(name: "Slap", str: 1, hp: 1, description: "What did the five fingers say to the face?", user_id: u1.id, item_id: i4.id)
Power.create(name: "Sanitize", str: 1, hp: 1, description: "99.98% effective", user_id: u2.id, item_id: i1.id)
Power.create(name: "Fart", str: 1, hp: 1, description: "Putrid gas attack", user_id: u1.id, item_id: i5.id)
Power.create(name: "Fart", str: 1, hp: 1, description: "Putrid gas attack", user_id: u2.id, item_id: i5.id)
